#!/bin/bash
source /home/steven/Documents/GITHUB/NMTModelAttack/ma/bin/activate

ROOT=/home/steven/Documents/GITHUB/NMTModelAttack
DATA=$ROOT/dataset/fr-en-raw
SRC=fr
TRT=en
EPOCH=30

#python spm_train.py \
#    --input=$DATA/wmt17_without_un.$SRC,$DATA/wmt17_without_un.$TRT \
#    --model_prefix=$DATA/sentencepiece \
#    --vocab_size=36000 \
#    --character_coverage=1.0 \
#    --model_type=bpe \

#python spm_encode.py \
#  --model $DATA/sentencepiece20k.model \
#  --output_format=piece \
#  --input $DATA/adv-baseline.$SRC $DATA/adv-baseline.$TRT \
#  --outputs $DATA/test-baseline.bpe.$SRC $DATA/test-baseline.bpe.$TRT \
#  --min-len 1 --max-len 1020

python spm_encode.py \
  --model $DATA/fr-en40k.model \
  --output_format=piece \
  --input $DATA/train.$SRC $DATA/train.$TRT \
  --outputs $DATA/train.bpe.$SRC $DATA/train.bpe.$TRT \
  --min-len 1 --max-len 1020

