#!/bin/bash

source /home/steven/Documents/GITHUB/NMTModelAttack/ma/bin/activate
ROOT=/home/steven/Documents/GITHUB/NMTModelAttack
DATA=$ROOT/dataset/debug
Pretrain_Model=/home/steven/Documents/GITHUB/NMTModelAttack/pretrain_models/xlmr.base

fairseq-preprocess \
    --source-lang zh --target-lang en \
    --joined-dictionary \
    --srcdict $Pretrain_Model/xlmr_vocab.txt \
      --trainpref $DATA/train.bpe \
      --validpref $DATA/dev.bpe \
      --testpref $DATA/test.bpe \
      --destdir $ROOT/data-bin/debug \
    --workers 8