#!/bin/bash

source /home/steven/Documents/GITHUB/NMTModelAttack/ma/bin/activate
ROOT=/home/steven/Documents/GITHUB/NMTModelAttack


for percent in 20 15 10 5 1
do
  OUT=$ROOT/output/adv/adv-c40-p$percent.out
  fairseq-generate \
  /home/steven/Documents/GITHUB/NMTModelAttack/data-bin/20k \
  --task translation \
  --gen-subset test \
  --path /home/steven/Documents/GITHUB/NMTModelAttack/checkpoints/zh-en-noshare/checkpoint_best.pt \
  --batch-size 32 \
  --adv-gen \
  --adv-model-path /home/steven/Documents/GITHUB/NMTModelAttack/checkpoints/dual-mrt/zh-en/checkpoint40.pt \
  --adv-percent $percent \
  --lenpen 1.0 \
  --remove-bpe sentencepiece \
  --sacrebleu \
  -s zh \
  -t en \
  --beam 5 > $OUT
done


