#!/bin/bash

source /home/steven/Documents/GITHUB/NMTModelAttack/ma/bin/activate
ROOT=/home/steven/Documents/GITHUB/NMTModelAttack
DATA=$ROOT/data-bin/debug
Pretrain_Model=/home/steven/Documents/GITHUB/NMTModelAttack/pretrain_models/xlmr.base
Checkpoint=$ROOT/checkpoints/debug

fairseq-train $DATA \
    --cpu --max-epoch 5 \
    -s zh -t en \
    --arch transformer_wmt_en_de \
    --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 0.0005 --min-lr 1e-09 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --weight-decay 0.0\
    --max-tokens  4096   --save-dir $Checkpoint \
    --update-freq 1 \