seed: 12
monitor: kendall
metric_mode: max
early_stopping: True
patience: 1
min_delta: 0.0
save_top_k: 2
save_weights_only: True 
min_epochs: 1
max_epochs: 2
gradient_clip_val: 1.0
gpus: 1
batch_size: 4
accumulate_grad_batches: 4
loader_workers: 4

optimizer: Adam
learning_rate: 1.0e-05
layerwise_decay: 0.95
scheduler: constant

train_path: data/wmt-metrics/relative-ranks-17-18.csv
val_path: data/wmt-metrics/test19-relative-ranks.csv

model: CometRanker
nr_frozen_epochs: 0
encoder_model: XLMR
pretrained_model: xlmr.base

layer: mix
scalar_mix_dropout: 0.1
pool: avg
